### ISSUE TITLE
Demo project crashes with `UnsupportedOperationException` in CardContainer#getSelectedView

### ISSUE THREAD

**Issue by ViliusKraujutis** [kikoso/Swipeable-Cards#26] opened 2014-10-19 14:28 UTC
`CardContainer#getSelectedView()` throws `UnsupportedOperationException` and `AndTinderDemo` sample application crashes.

/cc @Dr-Emann added this stub method

**Comment by seshuvinay** [comment] 2015-01-31 05:01
I don't see this crash in any of my testing phones. But I see 100s of reports everyday in Google Play store. Any Fixes to avoid this crash?

**Comment by H0LiC** [comment] 2015-02-06 20:30
check CardContainer class, there is some throw new UnsupportedOperationException();, if you delete that code will work, but with some things incomplete....

**Comment by seshuvinay** [comment] 2015-02-07 06:25
Thank you. I have done that already. I could reproduce it if I turn on Talkback on any device. Pretty straight.

**Comment by legentz** [comment] 2015-02-12 20:05
@H0LiC What did you mean with "some things incomplete" ? 
I've removed the throwing parts and added a simple "return mTopCard" and seems to work now

**Comment by H0LiC** [comment] 2015-02-20 18:29
@legentz i will presume that this method has a reason, if it only has a throw UnsupportedOperationException(), i will guess it is incomplete...

**Comment by legentz** [comment] 2015-02-20 18:42
I thought you knew something more :) 
However IMHO that method is like that because it was never tested so hardly like all users are doing now . If you search online you'll find some tutorials that explain the right way to implement an AdapterView... you'll need to override 4 abstract methods and the ones we don't need/use will contain "throw new UnsupportedOperationException() ".

I've modified like shumin0809 done... no lag, it goes like a charm!

**Comment by H0LiC** [comment] 2015-02-23 19:19
Yes, i think you are right. And sorry i don't have more information about it :(.

**Comment by TiagoGouvea** [comment] 2015-06-30 13:21
I'm having it too.. changing the getSelectedView() method now.

For reference, the error stack:

java.lang.UnsupportedOperationException
at com.andtinder.view.CardContainer.getSelectedView(CardContainer.java:420)
at android.widget.AdapterView.onInitializeAccessibilityEvent(AdapterView.java:972)
at android.widget.AdapterView.onRequestSendAccessibilityEvent(AdapterView.java:947)
at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:739)
at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:743)
at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:743)
at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:743)
at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:5323)
at android.view.View.sendAccessibilityEventUnchecked(View.java:5304)
at android.view.View$SendViewStateChangedAccessibilityEvent.run(View.java:21039)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5343)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by vikashparajuli** [comment] 2015-11-26 07:57
@Override
    public View getSelectedView() {
        //throw new UnsupportedOperationException();
        return mTopCard;
    }

This solve my problem remove throw new UnsupportedOperationException(); and return mTopCard in CardContainer.java class

**Comment by palashgoel7** [comment] 2016-03-15 18:17
`@Override
public View getSelectedView() {
//throw new UnsupportedOperationException();
return null;
}`

This works well. I have tested this on Motorola Moto X.

**Comment by MatthewJamesBoyle** [comment] 2017-06-07 00:05
Can someone make a PR for the fix?

**Comment by kikoso** [comment] 2017-06-07 00:47
Has been fixed and committed.

**Closed by kikoso** 2017-06-07 00:47 UTC
